name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          # Temporarily remove husky from package.json to prevent prepare script from running
          npm pkg delete scripts.prepare
          # Install dependencies without husky
          npm ci --no-audit --prefer-offline --ignore-scripts
          # Re-add the prepare script for local development
          npm pkg set scripts.prepare="husky install"
        
      - name: Build
        run: |
          # Clean previous builds
          rm -rf .next out
          
          # Install dependencies properly
          npm ci --no-audit --prefer-offline
          
          # Build the application
          npm run build
          
          # Export to static files
          npm run export
          
          # Ensure proper permissions
          chmod -R 755 out/
          
          # Create necessary directories and copy files
          mkdir -p out/_next/static
          [ -d .next/static ] && cp -r .next/static out/_next/ || true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
